exclude_paths:
  - docs
  - example_postman
  - examples
  # skip the test directories because it the spec blocks aggressively show up as
  # duplicates
  - packages/node_modules/*/test
  - packages/node_modules/@ciscospark/*/test
  - packages/node_modules/@webex/*/test
  - src
  - test
