extends: "@webex/eslint-config-base"
globals:
  PACKAGE_VERSION: false
root: true
rules:
  # These rules should be moved to @ciscospark/eslint-config-base
  no-warning-comments: warn
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
        ArrowFunctionExpression: false
        FunctionExpression: true
  valid-jsdoc:
    - error
    -
      matchDescription: ".+"
      prefer:
        arg: param
        argument: param
        return: returns
        virtual: abstract
        fires: emits
      requireParamDescription: false
      requireReturn: false
      requireReturnType: true
      requireReturnDescription: false

  # These warnings are transitional during the change from the in-repo config to
  # our new style guide
  class-methods-use-this: warn
  max-len:
    - warn
    -
      ignoreComments: true
  no-multi-assign: warn
  no-param-reassign: warn
  no-shadow: warn
  no-underscore-dangle: warn
  import/first: warn
  import/order: warn
  prefer-destructuring:
    - error
    - VariableDeclarator:
        array: false
        object: true
      AssignmentExpression:
        array: false
        object: false
    - enforceForRenamedProperties: false
  no-use-before-define:
    - error
    -
      classes: false
      functions: false
      variables: true

overrides:
  # Reduce the severity of jsdoc violations
  # TODO move to the transitional section once the core section moves to core
  -
    files:
      - packages/node_modules/**/*.js
    rules:
      valid-jsdoc:
      - error
      -
        prefer:
          arg: param
          argument: param
          return: returns
          virtual: abstract
          fires: emits
        requireParamDescription: false
        requireReturn: true
        requireReturnType: true
        requireReturnDescription: false
      require-jsdoc:
        - warn
        - require:
            FunctionDeclaration: true
            MethodDefinition: true
            ClassDeclaration: true
            ArrowFunctionExpression: false
            FunctionExpression: true
  # Relax rules in tests
  -
    files:
      - 'packages/node_modules/**/test/**/*.js'
      - 'packages/node_modules/**/*-spec/**/*.js'
    env:
      mocha: true
    rules:
      func-names: 0
      no-invalid-this: 0
      require-jsdoc: 0
  # Set webdriver.io globals
  -
    files:
      - 'wdio.helpers.d/**/*.js'
      - 'packages/node_modules/**/test/wdio/**/*.js'
    globals:
      browser: false
      $: false
      $$: false
      step: false
  -
    files:
      - packages/node_modules/@webex/xunit-with-logs
    rules:
      func-names: 0
      no-console: 0
  # Allow cli tools to use sync methods
  -
    files:
      - packages/node_modules/**/bin-*/**
    rules:
      no-sync: 0
