env:
  mocha: true
plugins:
  - mocha
rules:
  arrow-body-style:
    - 0
  func-names:
    - 0
  max-nested-callbacks:
    - 0
  no-console:
    - 0
  no-extra-parens:
    # IIFEs don't get detected correctly
    - 0
  no-invalid-this:
    - 0
  no-shadow:
    - 0
  require-jsdoc:
    - 0
  mocha/no-exclusive-tests:
    - 2
