FROM node:4

ENV NPM_CONFIG_LOGLEVEL warn
ENV NPM_CONFIG_REGISTRY=http://engci-maven-master.cisco.com/artifactory/api/npm/webex-npm-group

ENV COVERAGE=TRUE
ENV SAUCE=TRUE
ENV XUNIT=TRUE
WORKDIR /var/log
