/*!
 * Copyright (c) 2026 Cisco Systems, Inc. See LICENSE file.
 */

/* eslint-disable no-console */

import * as fs from 'fs';
import * as path from 'path';

// The generated bootstrap file, required first so it can configure the shared
// webex-core config before any WebexCore instance is constructed. Not a dotfile,
// so karma's browserify preprocessor (which skips dotfiles) still bundles it.
const BOOTSTRAP_FILENAME = 'kms-caroots.bootstrap.js';

/**
 * Supplies the KMS CA roots to integration tests.
 *
 * @remarks
 * Generation is delegated to the publishable `@webex/kms-caroots` package (the
 * same tool consumers use). The roots are written into a bootstrap file that is
 * loaded before the tests so it can configure the shared webex-core config; the
 * KMS certificate is then validated against the real trust store.
 *
 * @public
 */
class KmsCaroots {
  /**
   * Generates the CA roots and writes a bootstrap file into a package under test
   * that configures the shared webex-core config before any WebexCore instance
   * is constructed. If generation fails (e.g. no network or openssl), it instead
   * disables KMS certificate validation so the suite can still run.
   *
   * @param packageRoot - The root directory of the package under test.
   * @returns - Promise resolving to the bootstrap file path and a cleanup
   *   function.
   */
  public static async prepareTestBootstrap(
    packageRoot: string,
  ): Promise<{ file: string; cleanup: () => void }> {
    const file = path.join(packageRoot, BOOTSTRAP_FILENAME);
    let body: string;

    try {
      // eslint-disable-next-line global-require, @typescript-eslint/no-var-requires
      const { generateKmsCaroots } = require('@webex/kms-caroots');
      const caroots = await generateKmsCaroots();

      console.log(`KMS CA roots: validating the KMS certificate against ${caroots.length} roots`);
      body = `config.encryption.caroots = ${JSON.stringify(caroots)};`;
    } catch (error) {
      console.warn(
        `KMS CA roots: generation failed (${(error as Error).message}); skipping KMS cert validation`,
      );
      body = 'config.encryption.shouldValidateKMSCertificate = false;';
    }

    const contents = `/* Generated by @webex/legacy-tools for KMS certificate validation. Do not edit or commit. */
try {
  var mod = require('@webex/webex-core/dist/config');
  var config = mod.default || mod;
  config.encryption = config.encryption || {};
  ${body}
} catch (error) {
  // webex-core is not part of this package's tests; nothing to configure.
}
`;

    fs.writeFileSync(file, contents);

    return {
      file,
      cleanup: () => {
        try {
          fs.unlinkSync(file);
        } catch (error) {
          // ignore
        }
      },
    };
  }
}

export default KmsCaroots;
