export const NOISE_REDUCTION_MODE = {
  NONE: 'AUDIO_BACKGROUND_NOISE_REDUCTION_NONE',
  LOW_POWER: 'AUDIO_BACKGROUND_NOISE_REDUCTION_LOW_POWER',
};

export const VIRTUAL_BACKGROUND_MODE = {
  NONE: 'VIDEO_BACKGROUND_AUGMENT_NONE',
  BLUR: 'VIDEO_BACKGROUND_AUGMENT_BLUR',
  REPLACE_IMAGE: 'VIDEO_BACKGROUND_AUGMENT_REPLACE_IMAGE',
  REPLACE_VIDEO: 'VIDEO_BACKGROUND_AUGMENT_REPLACE_VIDEO',
};
