/* eslint-disable require-jsdoc */
/* eslint-disable no-unused-expressions */
import {WebexPlugin} from '@webex/webex-core';
import {FileDownloadOptions, IEncryption} from './encryption.types';
import {ENCRYPTION} from './constants';
import {WebexSDK} from '../types';

/**
 * @description Encryption APIs for KMS
 * @class
 */
class Cypher extends WebexPlugin implements IEncryption {
  readonly namespace = ENCRYPTION;
  private readonly $webex: WebexSDK;

  constructor(...args: any[]) {
    super(...args);
    // @ts-ignore
    this.$webex = this.webex;
  }

  /**
   * Downloads and decrypts a file from the given URI.
   *
   * @param {string} fileUri - The URI of the file to be decrypted.
   * @param {FileDownloadOptions} options - The options for file download.
   * @returns {Promise<ArrayBuffer>} A promise that resolves to the decrypted ArrayBuffer.
   * @throws {Error} If the file download or decryption fails.
   *
   * @example
   * ```typescript
   * const decryptedBuf = await webex.cypher.downloadAndDecryptFile('https://example.com/encrypted-file?JWE=eyJhbGci&keyUri=kms://example.com/keys/1234', {useFileService: false});
   * const file = new File([decryptedBuf], "myFileName.jpeg", {type: 'image/jpeg'});
   * ```
   */
  public async downloadAndDecryptFile(
    fileUri: string,
    {useFileService = false, ...options}: FileDownloadOptions = {}
  ): Promise<ArrayBuffer> {
    // Sample fileUri: https://beta.webex.com/files/api/v1/spaces/4783c2-e139-4f24-a2d9-0302ee1a8a98/contents/419213bf-ed87-4655-950a-f04afbfea3df/versions/3a75cedf39434bde9d650bbe0ad24221/bytes?keyUri=kms://kms-usint.wbx2.com/keys/141686e6-9ftd-4tcf-8e-80718b95847557f96b&JWE=eyAiYWxnIjogImRpciIsICJlbmMiOifyndafRTI1NkdDTSIgfQ
    // KeyUri: An attachment level unique ID generated by Webex KMS post encryption of an attachment. In order to
    // decrypt an attachment, KeyUri is a required parameter.
    // JWE: JWE can be decrypted using KMS key to obtain the SCR key.
    // Decrypting an attachment requires the SCR key parameter.
    // We need to download the encrypted file from the given URI and then decrypt it using the SCR key.
    // The decrypted file is then returned.

    // step 1: parse the fileUri to get the keyUri and JWE
    // step 2: if keyUri and JWE are not present in the fileUri, use the options
    // step 3: use the keyUri to decrypt the JWE to get the SCR
    // step 4: download the file from the fileUri and decrypt it using the SCR

    // Parse the fileUri & JWE to get the keyUri using urlSearchParams
    const url = new URL(fileUri);
    let keyUri = url.searchParams.get('keyUri');
    let JWE = url.searchParams.get('JWE');

    // Check if the keyUri and JWE are present, else take it from options
    if (!keyUri || !JWE) {
      keyUri = options.keyUri;
      JWE = options.jwe;
    }

    // Check if the keyUri and JWE are present, else throw an error
    if (!keyUri || !JWE) {
      throw new Error(
        'KeyUri and JWE are required to decrypt the file. Either provide them in the fileUri or in the options.'
      );
    }

    try {
      // Decrypt the JWE to get the SCR
      const scr = await this.$webex.internal.encryption.decryptScr(keyUri, JWE);

      // Start the download and decryption process, returning a promise

      return this.$webex.internal.encryption.download(fileUri, scr, {useFileService});
    } catch (error) {
      throw new Error(`Failed to decrypt the JWE: ${error.message}`);
    }
  }
}

export default Cypher;
