# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1469577627);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1469574135379");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1469577735379");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160123151951");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1469577508");
user_pref("browser.slowStartup.averageTime", 12734);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20160123151951");
user_pref("browser.startup.homepage_override.mstone", "44.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1469660516777");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1469574178287");
user_pref("datareporting.policy.firstRunTime", "1469574116777");
user_pref("datareporting.sessions.current.activeTicks", 37);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 6700);
user_pref("datareporting.sessions.current.main", 5215);
user_pref("datareporting.sessions.current.sessionRestored", 6494);
user_pref("datareporting.sessions.current.startTime", "1469577501926");
user_pref("datareporting.sessions.current.totalTime", 206);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1469574099225,\"a\":6,\"t\":109,\"c\":true,\"m\":17213,\"fp\":19177,\"sr\":19075}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "44.0");
user_pref("extensions.lastPlatformVersion", "44.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/home/spark/Desktop/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0\",\"st\":1453599098000,\"mt\":1453599098000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":false,\"v\":\"2.7\",\"st\":1407427883000,\"mt\":1375741724000}}}");
user_pref("gecko.buildID", "20160123151951");
user_pref("gecko.mstone", "44.0");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1469574180);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160123151951");
user_pref("media.gmp-manager.lastCheck", 1469574179);
user_pref("media.peerconnection.video.h264_enabled", true);
user_pref("media.webrtc.debug.aec_log_dir", "/tmp");
user_pref("media.webrtc.debug.log_file", "/tmp/WebRTC.log");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 20894);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1469577507);
user_pref("toolkit.telemetry.cachedClientID", "6b249b35-f21b-4531-8a45-2b9fcd702c71");
user_pref("toolkit.telemetry.previousBuildID", "20160123151951");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
