#!/usr/bin/env node
/*!
 * Generates `docs/samples/web-extension-bridge-extension/manifest.json` from the template.
 *
 * The manifest is generated rather than committed for two reasons. The origin has to
 * match wherever the sample page is actually served from (this repo's dev server is
 * HTTPS on port 8000, not the 5173 a Vite-based reader might expect), and the "local
 * testing only" banner has to be impossible to miss when someone opens the file — so
 * it is injected as the first key on every build instead of relying on a comment that
 * JSON cannot carry anyway.
 */

import {readFile, writeFile} from 'node:fs/promises';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const ORIGIN_TOKEN = '__SAMPLE_ORIGIN__';
const ORIGIN_PATTERN = /^https?:\/\/[a-zA-Z0-9.-]+(:\d{1,5})?$/;
const BANNER =
  'LOCAL TESTING ONLY. Generated by scripts/prepare-samples.mjs; edits are overwritten. ' +
  'This manifest allow-lists a localhost dev origin and must never ship. Replace the ' +
  'content_scripts matches and host_permissions with your exact production origin, then ' +
  'work through the "Before you ship" checklist in the package README.';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const extensionDir = resolve(packageRoot, '../../../docs/samples/web-extension-bridge-extension');
const templatePath = resolve(extensionDir, 'manifest.template.json');
const manifestPath = resolve(extensionDir, 'manifest.json');

const origin = process.env.SAMPLE_ORIGIN ?? 'https://localhost:8000';

if (!ORIGIN_PATTERN.test(origin)) {
  process.stderr.write(
    `SAMPLE_ORIGIN must be an exact origin such as https://localhost:8000, got '${origin}'\n`
  );
  process.exit(1);
}

const template = await readFile(templatePath, 'utf8');

if (!template.includes(ORIGIN_TOKEN)) {
  process.stderr.write(`manifest.template.json no longer contains ${ORIGIN_TOKEN}\n`);
  process.exit(1);
}

// Parsed after substitution so a template that produces invalid JSON fails here rather
// than as an opaque "could not load manifest" in Chrome.
const manifest = JSON.parse(template.split(ORIGIN_TOKEN).join(origin));

await writeFile(manifestPath, `${JSON.stringify({_comment: BANNER, ...manifest}, null, 2)}\n`);

process.stdout.write(`wrote web-extension-bridge-extension/manifest.json for ${origin}\n`);
