export const AI_ASSISTANT_REGISTERED = 'aiassistant:registered';
export const AI_ASSISTANT_UNREGISTERED = 'aiassistant:unregistered';
export const ASSISTANT_API_RESPONSE_EVENT = 'event:assistant-api.response';
export const AI_ASSISTANT_SERVICE_NAME = 'assistant-api';
export const AI_ASSISTANT_RESULT = 'aiassistant:result';
export const AI_ASSISTANT_STREAM = 'aiassistant:stream';

export enum AI_ASSISTANT_ERRORS {
  NOT_ENOUGH_CONTENT = 'NO_ENOUGH_MEETING_TRANSCRIPT',
  TRANSCRIPT_AUTH_ERROR = 'TRANSCRIPT_AUTH_ERROR',
  AI_ASSISTANT_TIMEOUT = 'AI_ASSISTANT_TIMEOUT', // This one is generated by the plugin
}

export enum AI_ASSISTANT_ERROR_CODES {
  AI_ASSISTANT_TIMEOUT = 9408, // This one is generated by the plugin
  NOT_ENOUGH_CONTENT = 204,
  FORBIDDEN = 403,
  LLM_TIMEOUT = 408,
  RATE_LIMIT = 429,
  GENERIC_ERROR = 10000,
  WAIT_PREVIOUS = 10001,
  EMPTY_SEARCH_RESULT = 10002,
}

export enum ACTION_TYPES {
  SHOW_ALL_ACTION_ITEMS = 'SHOW_ALL_ACTION_ITEMS',
  WAS_MY_NAME_MENTIONED = 'WAS_MY_NAME_MENTIONED',
  SUMMARIZE_FOR_ME = 'SUMMARIZE_FOR_ME',
}

export enum CONTENT_TYPES {
  ACTION = 'action',
  MESSAGE = 'message',
}

export enum CONTEXT_RESOURCE_TYPES {
  MEETING = 'meeting',
}
