# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1469221717);
user_pref("app.update.lastUpdateTime.background-update-timer", 1469221469);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1469221837);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1469221226);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1469221596);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1469221346);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1469221957);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1469221194303");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1469222972303");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1469221123898");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1469224723898");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.defaultBrowserCheckCount", 1);
user_pref("browser.slowStartup.averageTime", 2671);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20160210153822");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1469307506046");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1469221168036");
user_pref("datareporting.policy.firstRunTime", "1469221106046");
user_pref("datareporting.sessions.current.activeTicks", 31);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2308);
user_pref("datareporting.sessions.current.main", 250);
user_pref("datareporting.sessions.current.sessionRestored", 2711);
user_pref("datareporting.sessions.current.startTime", "1469221105318");
user_pref("datareporting.sessions.current.totalTime", 1030);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1469221723);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455153185000,\"mt\":1455151923000}}}");
user_pref("gecko.buildID", "20160210153822");
user_pref("gecko.mstone", "44.0.2");
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.crash-guard.glcontext.appVersion", "44.0.2");
user_pref("gfx.crash-guard.glcontext.deviceID", "0x162b");
user_pref("gfx.crash-guard.status.glcontext", 2);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3-u-i386-x86_64");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1469221171);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160210153822");
user_pref("media.gmp-manager.lastCheck", 1469221168);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1469221105);
user_pref("toolkit.telemetry.cachedClientID", "85d5d896-b3bd-eb40-a82e-bf817e2c58fa");
user_pref("toolkit.telemetry.previousBuildID", "20160210153822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
