source "https://rubygems.org"

# Jekyll via GitHub Pages
gem "github-pages", ">= 175", group: :jekyll_plugins

# Jekyll Theme
gem "minima", "~> 2.0"

# Jekyll Plugins
group :jekyll_plugins do
   gem "jekyll-redirect-from", "~> 0.12"
end
