source "https://rubygems.org"

# Jekyll via GitHub Pages
gem "github-pages", ">= 207", group: :jekyll_plugins

# Jekyll Theme
gem "minima", "~> 2.1", ">= 2.1.1"

# Jekyll Plugins
group :jekyll_plugins do
   gem "jekyll-redirect-from", "~> 0.12", ">= 0.12.1"
end
