export const CALL_HISTORY_ANSWERED_DISPOSITIONS = ['ANSWERED', 'INITIATED'];
export const CALL_HISTORY_MISSED_CALLER_DISPOSITIONS = ['CANCELED', 'INITIATED'];
export const CALL_HISTORY_REJECTED_CALLER_DISPOSITIONS = ['CANCELED', 'INITIATED'];
export const CALL_HISTORY_REJECTED_CALLEE_DISPOSITIONS = ['REJECTED', 'MISSED', 'CANCELED'];

export const CALL_HISTORY_TIME_LOOKBACK_MS = 5000;
export const CALL_HISTORY_RECENT_RECORD_TOLERANCE_MS = 120000;
export const CALL_HISTORY_COUNTERPART_MATCH_MIN_DIGITS = 4;
export const CALL_HISTORY_URL_PATTERN = '**/history/userSessions**';
export const CALL_HISTORY_EVENTUAL_CONSISTENCY_TIMEOUT = 150000;
export const CALL_HISTORY_POLL_INTERVALS = [5000, 5000, 10000, 10000, 15000];
export const CALL_HISTORY_TIMING_TOLERANCE_MS = 120000;
export const CALL_HISTORY_DURATION_TOLERANCE_SECONDS = 120;
